---
apiVersion: v1
metadata:
  labels:
    app.kuberentes.io/name: {{ include "ucentralfms.name" . }}
    helm.sh/chart: {{ include "ucentralfms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "ucentralfms.fullname" . }}-config
kind: Secret
type: Opaque
data:
  ucentralfms.properties: {{ include "ucentralfms.config" . | b64enc }}
